name: Eva Application Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  evaapp:
    name: Run eva application tests
    runs-on: ubuntu-latest
    steps:
    - name: Install ubuntu dependencies
      run: |
        sudo apt-get install libproj-dev proj-data proj-bin
        sudo apt-get install libgeos-dev musl-dev libc-dev
        sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
    - name: Clone eva repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install eva and dependencies
      run: pip install --use-deprecated=legacy-resolver -r requirements-github.txt --user .
    - name: Put eva in the path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Check eva path
      run: which eva_tests
    - name: Run eva applications tests
      run: eva_tests application
