name: Eva Application Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PYTHONPATH: /home/runner/.local/lib/python3.9/site-packages

jobs:
  evaapp:
    name: Run eva application tests
    runs-on: ubuntu-latest
    steps:
    - name: Install ubuntu dependencies
      run: |
        sudo apt-get install libproj-dev proj-data proj-bin
        sudo apt-get install libgeos-dev musl-dev libc-dev
        sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install --upgrade pip
    - run: pip install netCDF4 --user
    - run: pip install --use-deprecated=legacy-resolver -r requirements-github.txt --user .
    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - run: echo $GITHUB_PATH; echo $PYTHONPATH
    - run: ls -lrt /home/runner/.local/lib/python3.9/site-packages/eva/tests/data/amsua_n19.hofx.2020-12-14T21:00:00Z.nc4
    - run: eva_tests application
